language: python
dist: xenial
python:
  - 3.6
install:
  - pip install pipenv
  - pipenv install --deploy --dev
script:
  - ./manage.py migrate
  - PYTHONWARNINGS=always coverage run manage.py test
  - flake8 .
  - yapf -dr .
  - mypy .
  - pydocstyle
  - safety check
  - pip install "git+https://github.com/${TRAVIS_REPO_SLUG}.git#egg=ndh"
after_success:
  - coveralls
